### ISSUE TITLE
non-working failregex in fail2ban-subnets.py

### ISSUE THREAD

**Issue by timber74** [XaF/fail2ban-subnets#1]
I'm using fail2ban 0.8.13 and the failregex in the python script wasn't matching entries in my fail2ban.log. I edited the failregex as follows and it seems to be working now.

`failregex = ('%(time)s fail2ban\.actions\[\d+\]:(?: [A-Z]+)? ' +
             '\[(?!%(donotmatchjail)s\])(?P<JAIL>.*)\] ' +
             'Ban (?P<HOST>(?:[0-9]{1,3}\.){3}[0-9]{1,3})$')`

**Comment by xaf** [comment]
Thanks for the report! I'll patch that to make it work with old as well as new versions!
